# Generated by Django 5.1.1 on 2024-09-21 15:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='id',
        ),
        migrations.AddField(
            model_name='events',
            name='event_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
